// Fallback authored-track sampler for builds without the pinned doldecomp/melee tree.
// The real implementation is generated by tools/generate_fobj_host.py from the decomp's
// fobj.c/spline.c. Returning false disables authored sub-frame animation only; simulation
// and the standard (non-authored) frame interpolation modes are unaffected.
// SPDX-License-Identifier: GPL-2.0-or-later
#ifndef _MSC_VER
#include "PackedAnimation.h"

namespace NativeMelee {
bool SamplePacked(const PackedTrack&, float, float&) { return false; }
}  // namespace NativeMelee

#endif  // !_MSC_VER
